###INSTALLATION AND ENVIRONMENT SETUP
Install `conda` for Colab environment by running the next cell.



In [ ]:
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/latest/download/Mambaforge-colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:23
🔁 Restarting kernel...


In [ ]:
!nvidia-smi

Fri Dec 23 14:28:03 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P0    29W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Set up the `conda` environment with the necessary libraries.

In [ ]:
%%shell
conda create --name env python=3.8 -y
source activate env
conda install pytorch torchvision torchaudio -c pytorch-lts -c nvidia

python -m pip install -U pip
pip install --upgrade setuptools

pip install ninja
git clone https://github.com/facebookresearch/detectron2.git
python -m pip install -e detectron2

git clone https://github.com/facebookresearch/Detic.git --recurse-submodules
cd Detic
pip install -r requirements.txt

Solving environment: \ | done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /usr/local/envs/env

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.12.7  |       ha878542_0         143 KB  conda-forge
    setuptools-65.6.3          |     pyhd8ed1ab_0         619 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         761 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge None
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu None
  bzip2              conda-forge/linux-64

In [ ]:
%%shell
source activate env
pip install --upgrade daam
pip install accelerate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 49.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 453.1/453.1 kB 37.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 94.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 93.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 48.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 98.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 95.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 104.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 kB 14.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 kB

In [ ]:
%%shell
source activate env
pip show daam

Name: daam
Version: 0.0.12
Summary: What the DAAM: Interpreting Stable Diffusion Using Cross Attention.
Home-page: https://github.com/castorini/daam
Author: Raphael Tang
Author-email: r33tang@uwaterloo.ca
License: MIT
Location: /usr/local/envs/env/lib/python3.8/site-packages
Requires: diffusers, ftfy, gradio, inflect, joblib, nltk, numba, pandas, scikit-image, spacy, transformers
Required-by: 


In [ ]:
# Note that this doesn't work bcoz each command prefixed with ! executes in its own shell; the next cell works though bcoz it is executed in a single shell (* shows the currently active env)
!source activate env
!conda env list

# conda environments:
#
base                     /usr/local
env                      /usr/local/envs/env



In [ ]:
%%shell
source activate env
conda env list

# conda environments:
#
base                     /usr/local
env                   *  /usr/local/envs/env



In [ ]:
%%shell
source activate env
python -m pip install huggingface_hub

huggingface-cli login

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To login, `huggingface_hub` now requires a token generated from https://huggingface.co/settings/tokens .
    
Token: 
Add token as git credential? (Y/n) Y
Token is valid.
Cannot authenticate through git-credential as no helper is defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hu

In [ ]:
%%shell
source activate env
pip install diffusers transformers gradio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
%%bash
source activate env
python

import torch
print(torch.__version__)

1.13.1+cu117


In [ ]:
%%shell
source activate env
pip install ipykernel

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.2/145.2 kB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.8/116.8 kB 15.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.5/133.5 kB 15.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 41.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 83.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 761.7/761.7 kB 61.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 424.0/424.0 kB 43.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.4/386.4 kB 37.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 57.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 68.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━

In [ ]:
%%shell
source activate env
pip install -U jupyter_console

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
%%bash
source activate env
python

import nltk 
nltk.download('stopwords') 
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


In [ ]:
%%bash
source activate env
python

import os

if not os.path.exists("data/bboxes") : 
  os.makedirs("data/bboxes")

if not os.path.exists("data/heatmaps") : 
  os.makedirs("data/heatmaps")

if not os.path.exists("data/images") : 
  os.makedirs("data/images")

if not os.path.exists("bbox_output") : 
  os.mkdir("bbox_output")

The following is an implementation of the single image pipeline. You can try it out to get an idea of the outputs obtained and check the comparison with the `Detic` baseline.

In [32]:
%%bash
source activate env
python

import os 
import json
import cv2
import numpy as np
import torch
from PIL import Image
from daam import trace, set_seed
from diffusers import StableDiffusionPipeline

import nltk
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize

prompt = "little girl wearing pink dress standing in wooden cabin"
stop_words = set(stopwords.words('english'))

# Extracting nouns from prompt
tokenized = sent_tokenize(prompt)
nouns = []
for i in tokenized:
    wordsList = word_tokenize(i)
 
    wordsList = [w for w in wordsList if not w in stop_words]
    tagged = pos_tag(wordsList)
 
    nouns = [word for word, tag in tagged if tag == 'NN']

image_id = "1"
gen = set_seed(1)

bbox_path = "bboxes"
bbox_output_path = "bbox_output"
json_path = "json_path_matches"
thresh_path = "thresh_image"
genimg_path = "generated_image"
heatmaps_path = "heatmaps"
daam_output_path = "daam_output"
contour_points_path = "contour_points"

json_dict = dict()

model_id = 'stabilityai/stable-diffusion-2'
device = 'cuda'

pipe = StableDiffusionPipeline.from_pretrained(model_id, use_auth_token=True, torch_dtype=torch.float16, revision="fp16")
pipe = pipe.to(device)

with torch.cuda.amp.autocast(dtype=torch.float16), torch.no_grad():
    with trace(pipe) as tc:
        out = pipe(prompt, num_inference_steps=10, generator=gen)       # generate output from Stable Diffusion pipe
        img = out.images[0]   

        image_path = genimg_path + os.sep + image_id + os.sep + "generated_image.png"
        if not os.path.exists(genimg_path + os.sep + image_id + os.sep) : 
          os.mkdir(genimg_path + os.sep + image_id + os.sep)
        img.save(image_path)                                            # save generated image

        glob_heat_map = tc.compute_global_heat_map(prompt)              # generate global heat map

        for word in nouns : 
          heat_map = glob_heat_map.compute_word_heat_map(word)          # compute word-wise heatmap

          out_file = daam_output_path + os.sep + image_id + os.sep + word + os.sep + "daam_output.png"
          if not os.path.exists(daam_output_path + os.sep + image_id + os.sep + word + os.sep) : 
            os.makedirs(daam_output_path + os.sep + image_id + os.sep + word + os.sep)

          # create a new black image of same dimensions as original image, and overlay heat map on it
          img_shape = np.array(img).shape
          new_img = Image.fromarray(np.zeros(img_shape, dtype = np.uint8))
          heat_map.plot_overlay(new_img, out_file=out_file)         # overlay word-wise heatmap on generated img and save it

          real_image = cv2.imread(image_path)                   # read original (generated) image 
          real_image = cv2.resize(real_image, (369, 368),       # shrink it to the size of daam output image
               interpolation = cv2.INTER_AREA)
          print("Image dimensions for original image : {}, {}".format(real_image.shape[0], real_image.shape[1]))
          image =  cv2.imread(out_file)                         # read word-wise heat map image
          image = image[59:427, 144:513]                        # crop out the relevant portion from image
          print("Image dimensions for word heatmap : {}, {}".format(image.shape[0], image.shape[1]))
      
          # obtaining bboxes from heatmaps
          gray =  cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
          thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

          # saving thresholded images
          thr_path = thresh_path + os.sep + image_id + os.sep + word + os.sep + "thresh.png"
          os.makedirs(thresh_path + os.sep + image_id + os.sep + word + os.sep, exist_ok=True)
          cv2.imwrite(thr_path, thresh)

          # finding contours from thresholded images
          cnts = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
          cnts = cnts[0] if len(cnts) == 2 else cnts[1]
          print("Length of cnts for {} : {}".format(word, len(cnts)))

          # draw bbox rectangles on image
          bbox_image = image.copy()
          bb_out_path = bbox_output_path + os.sep + image_id + os.sep + word + os.sep + "daam_bbox.png"
          bb_path = bbox_path + os.sep + image_id + os.sep + word + os.sep
          os.makedirs(bbox_output_path + os.sep + image_id + os.sep + word + os.sep, exist_ok=True)   # create path for saving bbox_output
          os.makedirs(bbox_path + os.sep + image_id + os.sep + word + os.sep, exist_ok=True)        # create path for saving bboxes

          num_bboxes = 0
          word_bbox_paths = []
          for c in cnts:
              x, y, w, h = cv2.boundingRect(c)
                                                            # threshold for bbox size set bcoz minute disturbances in heat-map
              if w > 50 and h > 50:                       # are also detected as contours, and will be drawn on image
                cv2.rectangle(real_image, (x, y), (x + w, y + h), (0,255,0), 2)
                cv2.putText(real_image, word, (x+10, y+20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
                print("x : {}, y : {}, w : {}, h : {}".format(x, y, w, h))
                bbox_dims = np.array([x, y, w, h])

                # save bbox coordinates for each word
                np.save(bb_path + str(num_bboxes), bbox_dims)
                word_bbox_paths.append(bb_path + str(num_bboxes)+".npy")
                num_bboxes += 1

          json_dict[word] = word_bbox_paths
          cv2.imwrite(bb_out_path, real_image)

          t_path = thresh_path +  os.sep + image_id + os.sep + word + os.sep + "thresh.png"

          if not os.path.exists(thresh_path +  os.sep + image_id + os.sep + word + os.sep):
            os.makedirs(thresh_path + os.sep + image_id + os.sep + word + os.sep)

          cv2.imwrite(t_path, thresh)

# save bbox paths dictionary in JSON format
with open("bbox_paths.json", "w") as f:
    json.dump(json_dict, f)

# **DETIC**

First, copy the generated image to the `Detic` folder and then run `Detic` model for object detection.

In [ ]:
%%shell
cp generated_image/1/generated_image.png Detic/

In [ ]:
%%shell
source activate env
python -m pip install -e detectron2

cd Detic
mkdir models

wget https://dl.fbaipublicfiles.com/detic/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth -O models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth
python demo.py --config-file configs/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.yaml --input generated_image.png --output detic_output.png --vocabulary lvis --opts MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth

Display the `DAAM` annotated output for the image with given `word` and `image_id` ...

In [ ]:
import cv2
import numpy as np
import os 
from google.colab.patches import cv2_imshow

image_id = "1"
word = "dress"
bbox_img_path = "/content/bbox_output/"+image_id+"/"+word+"/daam_bbox.png"

img = cv2.imread(bbox_img_path)
cv2_imshow(img)

Next, we display the corresponding output for the `Detic` model .../

In [ ]:
import cv2
import numpy as np
import os 
from google.colab.patches import cv2_imshow

detic_output_path = "/content/Detic/detic_output.png"

output_img = cv2.imread(detic_output_path)
cv2_imshow(output_img)

Finally, we overlay the bboxes obtained using `DAAM` on the `Detic` output image. 

In [ ]:
import cv2
import numpy as np
import os 
import json
from google.colab.patches import cv2_imshow

image_id = "1"
word_list = ['cabin', 'dress', 'pink']
real_img_path = "Detic/detic_output.png"
img = cv2.imread(real_img_path)
img = cv2.resize(img, (369, 368), interpolation = cv2.INTER_AREA)     # shrink the image

with open("bbox_paths.json", "r") as f:
    json_dict = json.load(f)

    for word in word_list:
        bbox_path_list = json_dict[word]
        for bbox_path in bbox_path_list:
            x, y, w, h = np.load(bbox_path)
            cv2.rectangle(img, (x, y), (x + w, y + h), (0,255,0), 2)
            cv2.putText(img, word, (x+10, y+20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)

cv2.imwrite("daam+detic_output_final.png", img)
cv2_imshow(img)

# Building the Flickr30k pipeline

Now, we will import the `Flickr30k` captions and use the above single-image pipeline to create annotated data for object detection.

First, we'll mount Google drive to load the `flickr30k_all.json` file that contains the captions we will work on. 

Alternatively, the file can be downloaded from [here](https://bit.ly/3YI8dLQ) and uploaded to Colab.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


###CREATING DIRECTORIES

`data/bboxes` : path for storing word-wise bbox annotations for instances of the word detected in images

`data/heatmaps` : path for storing word-wise attention maps (heatmaps) for the word detected in images (as tensors)

`data/heatmap_imgs` : path for storing word-wise attention maps overlayed on dark background (as images)

`data/images` : path for storing the images generated using Stable Diffusion.



In [ ]:
%%bash
source activate env
python

import os

if not os.path.exists("data/bboxes") : 
  os.makedirs("data/bboxes")

if not os.path.exists("data/heatmaps") : 
  os.makedirs("data/heatmaps")

if not os.path.exists("data/heatmap_imgs") : 
  os.makedirs("data/heatmap_imgs")

if not os.path.exists("data/images") : 
  os.makedirs("data/images")

###CREATING ANNOTATED DATA

The captions used for generating images using Stable Diffusion are obtained from the `flickr30k_all.json` file, which contains a total of 150k captions for 30k images in the Flickr30k dataset.

- Model used : `stabilityai/stable-diffusion-2`
- Only stop-word removal has been used for obtaining words from captions.
- Due to computational constraints, the maximum number of generated images is limited by the `max_iter` parameter, which is set to 30. This can be set to any value <= 150k, the total number of captions in the dataset.


###DIRECTORY STRUCTURE

> `data/bboxes/{word}/{image_id}.npy` : contains bbox annotations for ALL instances of word in image with `image_id`.

> `data/heatmaps/{word}/{image_id}.pt` : contains attention maps (heatmaps) for word in image with `image_id`.

> `data/bboxes/{word}/{image_id}.png` : contains heatmaps overlayed on dark background for word in image with `image_id`.

> `data/images/{image_id}.png` : contains generated images.








In [27]:
%%bash
source activate env
cd data
python 

import os 
import json
import cv2
import numpy as np
import torch
from PIL import Image
from daam import trace, set_seed
from diffusers import StableDiffusionPipeline

import nltk
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))

# function to preprocess tokens of a prompt
def preprocess_tokens(tokens): 
  wordsList = [w for w in tokens if not w in stop_words]
  tokens_ = list(set(wordsList))            # remove repeated words

#   tagged = pos_tag(wordsList)               # apply POS tagging
#   tokens_ = [word for word, tag in tagged if tag == 'NN']     # extract nouns
  return tokens_

# Load dataset captions
print("Loading Flickr30k captions ...")
captions_path = '/content/drive/MyDrive/AIISC/data/flickr30k_all.json'
captions_dict = dict()

with open(captions_path, "r") as f:
  captions_dict = json.load(f)

# define directory names
bbox_path = "bboxes"
genimg_path = "images"
heatmaps_path = "heatmaps"
heatmap_imgs_path = "heatmap_imgs"

gen = set_seed(0)
image2word = dict()           # dictionary to store generated image id with corresponding list of caption words

model_id = 'stabilityai/stable-diffusion-2'
device = 'cuda'

# Load Stable Diffusion model pipeline
print("Loading model ...")
pipe = StableDiffusionPipeline.from_pretrained(model_id, use_auth_token=True, torch_dtype=torch.float16, revision="fp16")
pipe = pipe.to(device)
print("Model used : ", model_id)

# Temporary flag variable to limit no. of iterations
is_looping = True
max_iter = 30

for i, img_dict in enumerate(captions_dict['images']):
  
  if not is_looping:        # flag variable check
    break
  for j, sentence_dict in enumerate(img_dict['sentences']):

    prompts_per_img = len(img_dict['sentences'])
    idx = i * prompts_per_img + j           # compute image_id
    image_id = str(idx)

    # flag variable check
    if idx >= max_iter:
        is_looping = False
        break

    tokens = sentence_dict['tokens']
    prompt = sentence_dict['raw']
    tokens = [token.lower() for token in tokens]
    tokens = preprocess_tokens(tokens)
    image2word[image_id] = tokens           # save image_id with corresp caption tokens

    print("Generating image for image id {} ...".format(image_id))

    with torch.cuda.amp.autocast(dtype=torch.float16), torch.no_grad():
      with trace(pipe) as tc:
        out = pipe(prompt, num_inference_steps=10, generator=gen)       # generate output from Stable Diffusion pipe
        img = out.images[0]   

        # save generated image
        image_path = genimg_path + os.sep + image_id + ".png"
        if not os.path.exists(genimg_path) : 
          os.makedirs(genimg_path)
        img.save(image_path)                                            

        glob_heat_map = tc.compute_global_heat_map(prompt)              # generate global heat map

        for word in tokens : 
          try:
            heat_map = glob_heat_map.compute_word_heat_map(word)          # compute word-wise heatmap
          except:
            continue

          # save heatmap (tensor) as .pt file
          hmap_path = heatmaps_path + os.sep + word + os.sep + image_id + ".pt"
          if not os.path.exists(heatmaps_path + os.sep + word) : 
            os.makedirs(heatmaps_path + os.sep + word)
          torch.save(heat_map, hmap_path)
          
          hmap_img_path = heatmap_imgs_path + os.sep + word + os.sep + image_id + ".png"
          if not os.path.exists(heatmap_imgs_path + os.sep + word) : 
            os.makedirs(heatmap_imgs_path + os.sep + word)

          # create a new black image of same dimensions as original image, and overlay heat map on it
          img_shape = np.array(img).shape
          mono_img = Image.fromarray(np.zeros(img_shape, dtype = np.uint8))
          heat_map.plot_overlay(mono_img, out_file=hmap_img_path)                       # overlay word-wise heatmap on generated img and save it

          real_image = cv2.imread(image_path)                   # read original (generated) image 
          real_image = cv2.resize(real_image, (369, 368),       # shrink it to the size of daam output image
               interpolation = cv2.INTER_AREA)

          image = cv2.imread(hmap_img_path)                     # read word-wise heat map image
          # print("Image shape : ", image.shape)
          image = image[59:427, 144:513]                        # crop out the relevant portion from image
      
          # obtaining bboxes from heatmaps
          gray =  cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
          thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

          # finding contours from thresholded images
          cnts = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
          cnts = cnts[0] if len(cnts) == 2 else cnts[1]
          # print("Length of cnts : ", len(cnts))

          # define path for bbox
          bb_path = bbox_path + os.sep + word + os.sep + image_id + ".npy"
          os.makedirs(bbox_path + os.sep + word + os.sep, exist_ok=True)        

          # draw bbox rectangles on image
          bbox_image = image.copy()

          word_bboxes = []
          print("Checking contours ...")

          for c in cnts:
              x, y, w, h = cv2.boundingRect(c)
              # print("x : {}, y : {}, w : {}, h : {}".format(x, y, w, h))

              bbox_dims = np.array([x, y, w, h])
              word_bboxes.append(bbox_dims)

          # save bbox coordinates for each word
          word_bboxes = np.array(word_bboxes)
          np.save(bb_path, word_bboxes)

# save image2word dictionary in JSON format
with open("image2word.json", "w") as f:
    json.dump(image2word, f)    

Loading Flickr30k captions ...
Loading model ...
Model used :  stabilityai/stable-diffusion-2
Generating image for image id 0 ...
Image shape :  (480, 640, 3)
Length of cnts :  10
Checking contours ...
x : 77, y : 196, w : 3, h : 5
x : 97, y : 142, w : 6, h : 10
x : 35, y : 141, w : 40, h : 40
x : 91, y : 106, w : 16, h : 15
x : 305, y : 25, w : 47, h : 36
x : 360, y : 0, w : 9, h : 7
x : 319, y : 0, w : 17, h : 15
x : 58, y : 0, w : 256, h : 105
x : 93, y : 0, w : 9, h : 9
x : 56, y : 0, w : 20, h : 12
Image shape :  (480, 640, 3)
Length of cnts :  48
Checking contours ...
x : 123, y : 365, w : 2, h : 2
x : 233, y : 357, w : 1, h : 1
x : 107, y : 356, w : 13, h : 12
x : 121, y : 346, w : 8, h : 13
x : 329, y : 341, w : 1, h : 2
x : 104, y : 340, w : 1, h : 1
x : 200, y : 337, w : 4, h : 5
x : 335, y : 335, w : 8, h : 8
x : 325, y : 331, w : 5, h : 5
x : 116, y : 323, w : 1, h : 1
x : 229, y : 322, w : 5, h : 5
x : 346, y : 314, w : 3, h : 4
x : 264, y : 314, w : 5, h : 4
x : 170, y : 

100%|██████████| 10/10 [00:07<00:00,  1.34it/s]


### INFERENCE

For a given word, the inference pipeline performs `text-based image retrieval` and returns all images which contain instances of the word, along with the bboxes for those instances.

> `data/output/{word}/{image_id}.png` : Image with `image_id` annotated with bboxes for all instances of the search word.

In [28]:
%%bash
source activate env
cd data
python

import os
import cv2
import numpy as np

word = "girl"

cwd = os.getcwd()
bbox_path = cwd + os.sep + "bboxes" + os.sep + word
img_path = cwd + os.sep + "images" + os.sep
bboxes_list = os.listdir(bbox_path)

output_path = cwd + os.sep + "output" + os.sep + word
os.makedirs(output_path, exist_ok=True)

if len(bboxes_list) > 0 :
    for bbox_filename in bboxes_list:
        image_id = bbox_filename[:-4]
        bbox_file_path = bbox_path + os.sep + bbox_filename
        print("bbox file path : ", bbox_file_path)
        bboxes = np.load(bbox_file_path)
        print("bboxes : ",bboxes)

        image_path = img_path + image_id + ".png"
        print("Matching image : ", image_path)
        image = cv2.imread(image_path)
        image = cv2.resize(image, (369, 368),
              interpolation = cv2.INTER_AREA)

        for bbox in bboxes:
            x, y, w, h = list(bbox)
            print("x : {}, y : {}, w : {}, h : {}".format(x, y, w, h))
            cv2.rectangle(image, (x, y), (x + w, y + h), (0,255,0), 2)
            cv2.putText(image, word, (x+10, y+20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)

        out_path = output_path + os.sep + image_id + ".png"
        cv2.imwrite(out_path, image)

bbox file path :  /content/data/bboxes/girl/13.npy
bboxes :  [[154 230   3   3]
 [193 100  66 246]]
Matching image :  /content/data/images/13.png
x : 154, y : 230, w : 3, h : 3
x : 193, y : 100, w : 66, h : 246
bbox file path :  /content/data/bboxes/girl/12.npy
bboxes :  [[246 359   4   6]
 [242 349   3   7]
 [193 324   1   1]
 [181 290   2   3]
 [267 279   4   3]
 [174 275   4   4]
 [115 235   1   1]
 [159 233  17  10]
 [265 224  24  37]
 [274 215   3   2]
 [280 214   5   7]
 [149 213   2   1]
 [145 204   4   6]
 [146 192   4   4]
 [154 190   8  13]
 [128 186  17  19]
 [149 175   8  13]
 [138 170   4   9]
 [146 166   8   6]
 [135 161   3   7]
 [161 158   3   5]
 [153 148  13   7]
 [129 129   7  15]
 [135 118  15  37]
 [146 117  14   5]
 [123 110   3   3]
 [157 109  95 238]]
Matching image :  /content/data/images/12.png
x : 246, y : 359, w : 4, h : 6
x : 242, y : 349, w : 3, h : 7
x : 193, y : 324, w : 1, h : 1
x : 181, y : 290, w : 2, h : 3
x : 267, y : 279, w : 4, h : 3
x : 174, y : 

In case you need to delete the directory structure and start again, run the following cell ...

In [ ]:
%%bash
source activate env
python

import shutil

shutil.rmtree("bboxes")

shutil.rmtree("bbox_output")

shutil.rmtree("heatmaps")

shutil.rmtree("generated_image")

shutil.rmtree("thresh_image")

shutil.rmtree("json_path_matches")

shutil.rmtree("daam_output")

shutil.rmtree("contour_points")